### PR TITLE
Update to terraform-ls v0.25.2

### PR DESCRIPTION
**Pull request by TheSecEng**

### CODE REVIEW

**Comment by predragnikolic** [comment]
do you also want to add settings https://github.com/hashicorp/vscode-terraform/blob/main/package.json#L98
to sublime-package.json file?

**Comment by rchl** [comment]
> do you also want to add settings [https://github.com/hashicorp/vscode-terraform/blob/main/package.json#L98](https://github.com/hashicorp/vscode-terraform/blob/main/package.json?rgh-link-date=2022-02-26T21%3A30%3A14Z#L98) to sublime-package.json file?

That's the vscode extension setting and not really a server setting.
And also we already have equivalent as the user can just change the `command`.

**Review by rchl — APPROVED** [review]

**Comment by rchl** [comment]
There is something weird happening when the package updates the version on Mac. It looks like that results with the binary being blocked by the OS or something. Works after deleting downloaded binary and letting it download fresh copy.

**Comment by predragnikolic** [comment]
Was the error something like this?

https://github.com/hashicorp/terraform-ls/pull/43#issue-587305690

**Comment by rchl** [comment]
No. The binary would just exit with exit code -9.
I've checked file SHA and permissions and those were all identical as when it worked.
I have some security suite running on my Mac so maybe that's why.

**Pull request merged**
